spring.application.name: ncu

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=stock
    username: sa
    password: Oookkk205_
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

